const STORAGE_KEYS={tasks:"focusflow_tasks",habits:"focusflow_habits",countdown:"focusflow_countdown",theme:"focusflow_theme",focusStats:"focusflow_focus_stats",focusGoal:"focusflow_focus_goal",focusState:"focusflow_focus_state_v4"};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let tasks=load(STORAGE_KEYS.tasks,[]),habits=load(STORAGE_KEYS.habits,[]),countdown=load(STORAGE_KEYS.countdown,null),focusStats=load(STORAGE_KEYS.focusStats,{}),focusGoal=load(STORAGE_KEYS.focusGoal,120),filter="today";
let focus={minutes:25,remaining:1500,running:false,end:null,task:"",...load(STORAGE_KEYS.focusState,{})},timer;
const key=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function persist(){save(STORAGE_KEYS.tasks,tasks);save(STORAGE_KEYS.habits,habits);save(STORAGE_KEYS.countdown,countdown);save(STORAGE_KEYS.focusStats,focusStats);save(STORAGE_KEYS.focusGoal,focusGoal);save(STORAGE_KEYS.focusState,focus)}
function scheduled(h,d=new Date()){const n=d.getDay();return h.schedule==="daily"||(h.schedule==="weekdays"&&n>0&&n<6)||(h.schedule==="weekends"&&(n===0||n===6))}
function renderTasks(){const list=$("#taskList"),today=key();list.innerHTML="";let shown=tasks.filter(t=>filter==="all"||filter==="completed"&&t.completed||filter==="upcoming"&&!t.completed&&t.dueDate>today||filter==="today"&&(!t.completed&&t.dueDate<=today||t.completed&&t.completedAt?.startsWith(today))).sort((a,b)=>Number(a.completed)-Number(b.completed)||a.dueDate.localeCompare(b.dueDate));shown.forEach(t=>{const n=$("#taskTemplate").content.cloneNode(true),a=$(".task-item",n);a.classList.toggle("completed",t.completed);$(".task-check",n).checked=t.completed;$(".item-title",n).textContent=t.title;$(".item-meta",n).textContent=`${t.subject} • Due ${new Date(t.dueDate+"T00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}`;const p=$(".priority-badge",n);p.textContent=t.priority;p.classList.add(`priority-${t.priority}`);const due=$(".due-chip",n);due.textContent=t.completed?"Completed":t.dueDate<today?"Overdue":t.dueDate===today?"Today":"Upcoming";due.classList.add(t.completed?"done":t.dueDate<today?"overdue":t.dueDate===today?"today":"");$(".task-check",n).onchange=e=>{t.completed=e.target.checked;t.completedAt=t.completed?new Date().toISOString():null;persist();renderAll()};$(".delete-task",n).onclick=()=>{tasks=tasks.filter(x=>x.id!==t.id);persist();renderAll()};$(".edit-task",n).onclick=()=>{const title=prompt("Task title",t.title),subject=prompt("Subject",t.subject);if(title&&subject){t.title=title;t.subject=subject;persist();renderAll()}};$(".focus-task",n).onclick=()=>{$("#focusTaskSelect").value=t.id;focus.task=t.id;startFocus()};list.append(n)});$("#visibleTaskCount").textContent=`${shown.length} task${shown.length===1?"":"s"}`;$("#emptyTaskMessage").hidden=shown.length>0}
function streak(h){let s=0,d=new Date();while(true){if(scheduled(h,d)){if(!h.completedDates?.includes(key(d)))break;s++}d.setDate(d.getDate()-1)}return s}
function renderHabits(){const list=$("#habitList"),today=key();list.innerHTML="";habits.forEach(h=>{h.completedDates=h.completedDates||[];const n=$("#habitTemplate").content.cloneNode(true),done=h.completedDates.includes(today),ok=scheduled(h);$(".habit-item",n).classList.toggle("completed",done);$(".habit-check",n).checked=done;$(".habit-check",n).disabled=!ok;$(".item-title",n).textContent=h.name;$(".habit-streak",n).textContent=ok?`🔥 ${streak(h)} day streak • ${h.schedule}`:`Not scheduled today • ${h.schedule}`;$(".habit-check",n).onchange=e=>{h.completedDates=e.target.checked?[...new Set([...h.completedDates,today])]:h.completedDates.filter(x=>x!==today);persist();renderAll()};$(".delete-habit",n).onclick=()=>{habits=habits.filter(x=>x.id!==h.id);persist();renderAll()};$(".edit-habit",n).onclick=()=>{const name=prompt("Habit name",h.name);if(name){h.name=name;persist();renderAll()}};list.append(n)});const due=habits.filter(h=>scheduled(h)),done=due.filter(h=>h.completedDates.includes(today));$("#habitHeaderProgress").textContent=`${done.length}/${due.length}`;$("#emptyHabitMessage").hidden=habits.length>0;$("#weekSection").hidden=habits.length===0}
function renderWeek(){const box=$("#weekActivity");box.innerHTML="";let total=0,done=0;for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const hs=habits.filter(h=>scheduled(h,d)),x=hs.filter(h=>h.completedDates?.includes(key(d))).length,p=hs.length?Math.round(x/hs.length*100):0;total+=hs.length;done+=x;box.insertAdjacentHTML("beforeend",`<div class="week-day ${i===0?"today":""}"><div class="week-track"><div class="week-fill" style="height:${p}%"></div></div><span>${d.toLocaleDateString("en-IN",{weekday:"short"}).slice(0,2)}</span></div>`)}$("#weekCompletionText").textContent=`${total?Math.round(done/total*100):0}% complete`}
function focusOptions(){const s=$("#focusTaskSelect"),v=s.value||focus.task;s.innerHTML='<option value="">General study session</option>'+tasks.filter(t=>!t.completed).map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join("");s.value=v}
function updateFocus(){if(focus.running&&focus.end)focus.remaining=Math.max(0,Math.ceil((focus.end-Date.now())/1000));if(focus.running&&focus.remaining<=0){focus.running=false;focus.end=null;const mins=focus.minutes,today=key();focusStats[today]=(focusStats[today]||0)+mins;const t=tasks.find(x=>x.id===focus.task);if(t)t.focusMinutes=(t.focusMinutes||0)+mins;focus.remaining=focus.minutes*60;persist();clearInterval(timer);renderAll();return}const m=Math.floor(focus.remaining/60),s=focus.remaining%60;$("#focusClock").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;$("#focusStartPause").textContent=focus.running?"Pause":"Start focus";$("#focusStatus").textContent=focus.running?"Running":focus.remaining<focus.minutes*60?"Paused":"Ready";$("#focusStatus").className=`status-pill ${focus.running?"running":focus.remaining<focus.minutes*60?"paused":""}`;$$('.timer-preset').forEach(b=>b.classList.toggle("active",Number(b.dataset.minutes)===focus.minutes));persist()}
function startFocus(){focus.task=$("#focusTaskSelect").value;focus.running=true;focus.end=Date.now()+focus.remaining*1000;clearInterval(timer);timer=setInterval(updateFocus,250);updateFocus()}
function pauseFocus(){focus.remaining=Math.max(0,Math.ceil((focus.end-Date.now())/1000));focus.running=false;focus.end=null;clearInterval(timer);updateFocus()}
function overview(){const today=key(),due=tasks.filter(t=>!t.completed&&t.dueDate<=today),hs=habits.filter(h=>scheduled(h)),hd=hs.filter(h=>h.completedDates?.includes(today)),fd=focusStats[today]||0,total=due.length+hs.length,completed=tasks.filter(t=>t.completedAt?.startsWith(today)).length+hd.length,p=total?Math.round(completed/total*100):0;$("#todayProgressText").textContent=`${p}%`;$("#todayProgressRing").style.setProperty("--progress",p);$("#todayTaskMetric").textContent=due.length;$("#todayHabitMetric").textContent=`${hd.length}/${hs.length}`;$("#todayFocusMetric").textContent=fd;$("#focusGoalMetric").textContent=focusGoal;$("#focusMinutesToday").textContent=fd;$("#focusGoalDisplay").textContent=focusGoal;$("#focusGoalInput").value=focusGoal;$("#focusGoalBar").style.width=`${Math.min(100,fd/focusGoal*100)}%`}
function milestone(){if(!countdown){$("#milestoneTitle").textContent="No exam or deadline set";$("#countdownDays").textContent=$("#countdownHours").textContent=$("#countdownMinutes").textContent="--";$("#clearCountdown").hidden=true;return}const diff=new Date(countdown.dateTime)-Date.now();if(diff<=0){$("#milestoneTitle").textContent=countdown.name;$("#milestoneDateText").textContent="Milestone reached";return}$("#milestoneTitle").textContent=countdown.name;$("#milestoneDateText").textContent=new Date(countdown.dateTime).toLocaleString("en-IN");$("#countdownDays").textContent=Math.floor(diff/86400000);$("#countdownHours").textContent=Math.floor(diff/3600000)%24;$("#countdownMinutes").textContent=Math.floor(diff/60000)%60;$("#clearCountdown").hidden=false}
function weekly(){const box=$("#weeklyBars");box.innerHTML="";let scores=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=key(d),hs=habits.filter(h=>scheduled(h,d)),hd=hs.filter(h=>h.completedDates?.includes(k)).length,td=tasks.filter(t=>t.completedAt?.startsWith(k)).length,fd=focusStats[k]||0,p=Math.round(((hs.length?hd/hs.length:0)+Math.min(1,td/2)+Math.min(1,fd/focusGoal))/3*100);if(p)scores.push(p);box.insertAdjacentHTML("beforeend",`<div class="weekly-day"><div class="weekly-track"><div class="weekly-fill" style="height:${p}%"></div></div><span>${d.toLocaleDateString("en-IN",{weekday:"short"}).slice(0,2)}</span></div>`)}const a=scores.length?Math.round(scores.reduce((x,y)=>x+y,0)/scores.length):0;$("#weeklyScore").textContent=`${a}%`}
function renderAll(){renderTasks();renderHabits();renderWeek();focusOptions();updateFocus();overview();milestone();weekly()}
const now=new Date();$("#currentDay").textContent=now.toLocaleDateString("en-IN",{weekday:"long"});$("#currentDate").textContent=now.toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"});$("#greeting").textContent=now.getHours()<12?"GOOD MORNING":now.getHours()<17?"GOOD AFTERNOON":"GOOD EVENING";
$("#themeToggle").onclick=()=>{const d=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=d;localStorage.setItem(STORAGE_KEYS.theme,d);$("#themeIcon").textContent=d==="dark"?"☀":"☾";$("#themeActionLabel").textContent=d==="dark"?"Light mode":"Dark mode"};
$("#taskDuePreset").onchange=e=>{$("#taskDueDate").hidden=e.target.value!=="custom"};$("#taskForm").onsubmit=e=>{e.preventDefault();const preset=$("#taskDuePreset").value,d=new Date();if(preset==="tomorrow")d.setDate(d.getDate()+1);if(preset==="week")d.setDate(d.getDate()+7);const due=preset==="custom"?$("#taskDueDate").value:key(d);tasks.push({id:id(),title:$("#taskTitle").value.trim(),subject:$("#taskSubject").value.trim(),dueDate:due,priority:$("#taskPriority").value,completed:false,createdAt:new Date().toISOString(),focusMinutes:0});e.target.reset();persist();renderAll()};
$$('.segment').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.segment').forEach(x=>x.classList.toggle("active",x===b));renderTasks()});$("#clearCompletedTasks").onclick=()=>{tasks=tasks.filter(t=>!t.completed);persist();renderAll()};
$("#habitForm").onsubmit=e=>{e.preventDefault();habits.push({id:id(),name:$("#habitName").value.trim(),schedule:$("#habitSchedule").value,completedDates:[],createdAt:new Date().toISOString()});e.target.reset();persist();renderAll()};
$$('[data-example-task]').forEach(b=>b.onclick=()=>{$("#taskTitle").value=b.dataset.exampleTask;$("#taskSubject").value="Physics"});$$('[data-example-habit]').forEach(b=>b.onclick=()=>{$("#habitName").value=b.dataset.exampleHabit});$$('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:"smooth",block:"center"}));
$$('.timer-preset').forEach(b=>b.onclick=()=>{if(!focus.running){focus.minutes=Number(b.dataset.minutes);focus.remaining=focus.minutes*60;updateFocus()}});$("#focusStartPause").onclick=()=>focus.running?pauseFocus():startFocus();$("#focusReset").onclick=()=>{focus.running=false;focus.end=null;focus.remaining=focus.minutes*60;clearInterval(timer);updateFocus()};$("#focusTaskSelect").onchange=e=>{focus.task=e.target.value;persist()};$("#focusGoalInput").onchange=e=>{focusGoal=Math.max(15,Math.min(600,Number(e.target.value)||120));persist();renderAll()};
$("#toggleMilestoneForm").onclick=()=>{$("#countdownForm").hidden=!$("#countdownForm").hidden};$("#countdownForm").onsubmit=e=>{e.preventDefault();countdown={name:$("#countdownName").value.trim(),dateTime:$("#countdownDate").value};persist();e.target.hidden=true;milestone()};$("#clearCountdown").onclick=()=>{countdown=null;persist();milestone()};
if(focus.running&&focus.end){timer=setInterval(updateFocus,250)}renderAll();setInterval(milestone,30000);
